language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
   - cpanm Alien::Base
   - cpanm -v --installdeps .

script:
   - perl ./Build.PL
   - ./Build
   - rm -f Alien-ImageMagick-*.tar.gz
   - ./Build dist
   - cpanm -v Alien-ImageMagick-*.tar.gz
